language: node_js
node_js:
  - "node"  # Latest stable Node.js version

addons:
  chrome: stable  # Ensure Chrome is available in Travis CI environment

before_install:
  # Set up ChromeDriver (update the version as necessary)
  - wget -N https://chromedriver.storage.googleapis.com/126.0.4/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
  - sudo chmod +x /usr/local/bin/chromedriver

install:
  # Install dependencies
  - npm install

before_script:
  # Start Chrome in headless mode
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  # Run Selenium tests
  - npm test
