name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: './GoogleChromeExtensionLeetCode/button'  # Adjusted path to match your repository structure
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjusted to a valid Node.js version

      - name: Install dependencies
        working-directory: ./GoogleChromeExtensionLeetCode/button  # Adjusted working directory path
        run: npm install

      - name: Run Selenium tests
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          npm run test
