name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./button
        run: npm install

      - name: Install necessary dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Selenium tests
        working-directory: ./button
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          export DISPLAY=:99.0
          sudo Xvfb :99 -ac &
          npm test
        env:
          CHROME_BIN: /usr/bin/google-chrome
          MOCHA_REPORTER: spec
